[project]
name = "cot-swapping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.5.0",
    "math-verify[antlr4-13-2]>=0.9.0",
    "openai>=2.17.0",
    "tqdm>=4.67.3",
]
